using Microsoft.Xaml.Behaviors;
using System;
using System.Threading.Tasks;
using System.Windows.Controls;

namespace ComputedBehaviors;

public class DataGridAutoGeneratingColumnLengthStarBehavior : Behavior<DataGrid>
{
    private double latestActualWidth = default;
    private bool autoGeneratedColumns = false;

    protected override void OnAttached()
    {
        AssociatedObject.AutoGeneratingColumn += OnAutoGeneratingColumn;
        AssociatedObject.AutoGeneratedColumns += OnAutoGeneratedColumns;
        base.OnAttached();
    }

    protected override void OnDetaching()
    {
        AssociatedObject.AutoGeneratingColumn -= OnAutoGeneratingColumn;
        AssociatedObject.AutoGeneratedColumns -= OnAutoGeneratedColumns;
        base.OnDetaching();
    }

    private async void OnAutoGeneratingColumn(object? sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (autoGeneratedColumns)
        {
            autoGeneratedColumns = false;
        }

        if (AssociatedObject.AutoGenerateColumns)
        {
            if (!autoGeneratedColumns)
            {
                e.Column.Width = new DataGridLength(latestActualWidth, DataGridLengthUnitType.Pixel);
            }

            await Task.Delay(1);
            e.Column.Width = new DataGridLength(1d, DataGridLengthUnitType.Star);
            await Task.Delay(1);

            latestActualWidth = e.Column.ActualWidth;
        }
    }

    private void OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        autoGeneratedColumns = true;
    }
}
